gc_test/gc_test/urls.py
from django.contrib import admin
from django.urls import path, include
#from .router import router
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('get_data.urls', namespace='get_data')),
   # path('', include('get_data.urls')),
    path('', include('pwa.urls')),
    #path('api/', include('show.url', namespace='result')),
    #path('api/', include('velocity.url', namespace='velocity'))

]

gc_test/get_data/urls.py
from django.urls import path
from django.views.generic import TemplateView
#from rest_framework.routers import DefaultRouter
#from .views import data_list
from .views import child_list
from .views import child_form
from .views import growth_checker
from .views import child_gr
from .views import height


#router = DefaultRouter('data', DataViewset)
app_name='get_data'

urlpatterns = [

   # path('data/', data_list),
    path('list/', child_list),
    path('growth/', child_gr),
    path('height/', height),
    path('form/', child_form),
    path('form/checker/', growth_checker),

]

gc_test/get_data/models.py
from django.db import models
from datetime import date

# Create your models here.
GENDER_CHOICES = (
    ("",'Select'),
    (0, 'girl'),
    (1, 'boy'),
)
class Data(models.Model):
    gender = models.IntegerField(choices=GENDER_CHOICES)
    age = models.FloatField(max_length=3)
    weight = models.FloatField(max_length=3) #change to float
    height = models.FloatField(max_length=3)
    dob = models.DateField()


  #  @property
  #  def age(self):
  #      if self.dob != None:
  #          self.age = date.today()-self.dob

gc_test/get_data/forms.py
from django import forms
from .models import Data
from datetime import date
#from.serializers import DataSerializer

class DateInput(forms.DateInput):
    input_type = 'date'



class childform(forms.ModelForm):

    class Meta:
        model = Data
        fields = ['gender', 'dob', 'weight', 'height', 'age']

       # def cal(self):
       #     return date.today() - self['dob']
        widgets = {
            'dob': DateInput()
        }
      #  fields['age'] = date.today() - fields['dob']






 #   def __init__(self, *args, **kwargs):
 #       super(childform,self).__init__(*args, **kwargs)
 #       self.fields['gender'].empty_label = "Select"

class chkform(forms.Form):
    age_when_last_weighed = forms.FloatField(label='Previous Age (in weeks)', max_value=100)
    previous_weight = forms.FloatField(label= 'Previous Weight (in kg) ', max_value=100)
    weight_at_birth = forms.FloatField(label= 'Weight at Birth (in kg) ', max_value=100)

gc_test/get_data/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from .models import Data
from .serializers import DataSerializer
from .forms import childform
from .forms import chkform
from .main import zone_main
from .growth_checker2 import checker
from .growth_velocity import velocity
from .length import zone_height
import requests
import json
import sys
# class ip:
#     ip_dic={}
#     flag=0
#     def init():

class inp:
    dict={}
    def set(self,dic):
        self.dict=dic
    def get(self):
        return self.dict
i = inp()

def child_list(request):
    return render(request,"get_data/child_list.html")

def child_gr(request):
    return render(request,"get_data/child_gr.html")

def height(request):
    return render(request,"get_data/height.html")

def child_form(request):
    if request.method == 'GET':
        form = childform()
        print(form)
        return render(request,'get_data/child_form.html',{'form':form})
    elif request.method == 'POST':
        if request.POST.get('main'):
            form= childform(request.POST)
            if form.is_valid():
                serializer = DataSerializer(data=form.data)
                if serializer.is_valid():
                    serializer.save()
                    dic=zone_main(serializer.data)
                    op= " Zone : " + str(dic['zone']) + '<br>' +"\n Minimum Weight Gain to reach Safe (Light Green) Zone : " + str(dic['minimum_healthy_weight']) + '<br>' + "\n Average Weight of a Healthy Child in this age group  :"+ str(dic['average_weight_for_child'])
                    return render(request,'get_data/child_list.html',{'op': op,'ip' : serializer.data})
                return JsonResponse(serializer.errors, status=400)
        elif request.POST.get('velocity'):
            form= childform(request.POST)
            if form.is_valid():
                serializer = DataSerializer(data=form.data)
                if serializer.is_valid():
                    serializer.save()
                    op=velocity(serializer.data)
                    return render(request,'get_data/child_list.html',{'op': op,'ip' : serializer.data})
                return JsonResponse(serializer.errors, status=400)
        elif request.POST.get('growth_ch'):
            form = childform(request.POST)
            if form.is_valid():
                serializer = DataSerializer(data=form.data)
                if serializer.is_valid():
                    serializer.save()
                    n_form=chkform()
                    i.set(serializer.data)
                  #  print(i.get())
                    request.method= 'POST'
                    return render(request,'get_data/growth.html', {'form':n_form })
                   # growth_checker(request,serializer.data)
                return JsonResponse(serializer.errors, status=400)
        elif request.POST.get('btn_height'):
           # print('test')
           # print('test')
            form = childform(request.POST)
            #field = form['height'].value()
            #field1 = form['weight'].value()
           # print(field)
           # print(field1)
           # print(form)
            if form.is_valid():
                print('form valid')
                print(form)
                serializer = DataSerializer(data=form.data)
                if serializer.is_valid():
                    print(serializer)
                    serializer.save()
                    dic = zone_height(serializer.data)
                    print(dic)
                    print(serializer.data)
                    op = " Zone : " + str( dic['zone']) + '<br>' + "\n Minimum Height Gain to reach Safe (Light Green) Zone : " + str(dic['minimum_healthy_height']) + '<br>' + "\n Average Height of a Healthy Child in this age group  :" + str(dic['average_height_for_child'])
                    print(op)
                    return render(request,'get_data/height.html',{'op': op,'ip' : serializer.data})
                return JsonResponse(serializer.errors, status=400)



def growth_checker(request):
    if request.method == 'POST':
        form= chkform(request.POST)
        if form.is_valid():
            f=form.data
            op=checker(f, i.get())
            print(op)
            print(f.dict())
            print(i.get())
            return render(request,'get_data/child_gr.html',{'op': op,'ip' : i.get(),'id': f.dict()})
    elif request.method == 'GET':
        form = chkform()
        return render(request, 'get_data/growth.html', {'form': form})
    return HttpResponse(form.errors, status=400)








# @csrf_exempt
# def data_list(request):
#
#     if request.method == 'GET':
#         data = Data.objects.all()
#         form = childform()
#         serializer = DataSerializer(data, many=True)
#         print(serializer.data)
#         return render(request, 'get_data/child_form.html', {'form': form})
#         #x = requests.post("http://127.0.0.1:8000/data", data=serializer.data )
#         #print(x.text)
#       #  return JsonResponse(serializer.data, safe=False)
#
#     elif request.method == 'POST':
#         data = JSONParser().parse(request)
#         serializer = DataSerializer(data =data)
#
#         if serializer.is_valid():
#             serializer.save()
#             print(serializer.data)
#
#             #x = requests.post("http://127.0.0.1:8000/data" , data= data)
#             #print(x.text)
#             return JsonResponse(serializer.data, status=201)
#         return JsonResponse(serializer.errors, status=400)

gc_test/templates/get_data/base.html
<!DOCTYPE html>
<html lang="en">
{% load pwa %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width-device-width", initial-scale="1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% progressive_web_app_meta %}
    <title>CHILD GROWTH CHECKER</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
</head>
<body>
<div class="container">
        <div class="col-md-10 offset-md-1 mt-5">
            <div class="jumbotron">
                <h2 class="display-4">Child Growth Checker</h2>
                <!--p class="lead font-italic">Base data entry</p-->
                <hr class="my-4">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

gc_test/templates/get_data/child_form.html
    {% extends "get_data/base.html" %}
    {% load crispy_forms_tags %}

    {% block content %}
    <!--p>form here</p-->
    <form action="" method="post" id="form"  >
        <input type="hidden" name="csrfmiddlewaretoken" value="2N18GERNhRs4ORqn29YgIdc2WIxQd4CdnYjgfTWS9fDv2Yii1iPHKbpG90HrSbIr">


        <div id="div_id_gender" class="form-group"> <label for="id_gender" class=" requiredField">
                Gender<span class="asteriskField">*</span> </label> <div class=""> <select name="gender" class="select form-control" required id="id_gender"> <option value="" selected>Select</option> <option value="0">girl</option> <option value="1">boy</option>

        </select> </div> </div> <div id="div_id_dob" class="form-group"> <label for="id_dob" class=" requiredField">
                Dob<span class="asteriskField">*</span> </label> <div class=""> <input type="date" name="dob" class="dateinput form-control" required id="id_dob"> </div> </div> <div id="div_id_weight" class="form-group"> <label for="id_weight" class=" requiredField">
                Weight<span class="asteriskField">*</span> </label> <div class=""> <input type="number" name="weight" step="any" class="numberinput form-control" required id="id_weight"> </div> </div> <div id="div_id_height" class="form-group"> <label for="id_height" class=" requiredField">
                Height<span class="asteriskField">*</span> </label> <div class=""> <input type="number" name="height" step="any" class="numberinput form-control" required id="id_height"> </div> </div> <div id="div_id_age" class="form-group"> <label for="id_age" class=" requiredField">
                Age<span class="asteriskField">*</span> </label> <div class=""><label type="number" id="cal_age"></label> <input type="number" name="age" step="any" class="numberinput form-control" required id="id_age"> </div> </div>


         <button type="submit" class="btn btn-success" value="main" name="main"> Check Weight Zone </button>
         <button type="submit" class="btn btn-success" value="btn_height" name="btn_height"> Check Height Zone </button>
         <button type="submit" class="btn btn-success" value="growth" name="growth_ch"> Growth Checker </button>
         <button type="submit" class="btn btn-success" value="velocity"  name="velocity"> Growth Velocity </button>
    </form>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js">
     </script>
    <script>
             $(function(){
                $("#id_age").hide()
                $("#id_dob").on('change', function(){
                 let dob=$(this).val();
                 var d=new Date(dob);
                 let today=new Date();
                 var age = (today-d)/(1000*60*60*24*7)
                 var week= Math.floor(age)
                 var days=Math.floor(((today-d)/(1000*60*60*24))%7)
                 $("#id_age").val(age.toFixed(2))
                 $("#cal_age").text(week+" week(s) "+days+" days")

                 console.log(dob,today,age);
                    })

              });


             let form = document.getElementById('form');
             /* let dob = form.elements['id_dob']; */

             /*let v = dob.value();*/
            /* alert(v)*/
            /* console.log(dob) */
            /* console.log(v) */
             const age = form.elements['id_age']
            /* age.value = 4 */
    </script>


<!--        <button type="submit" class="btn btn-success" onclick="child_form" > Check Zone </button>-->

    {% endblock content %}

gc_test/templates/get_data/child_list.html
<!DOCTYPE html>

  {% block content %}
  <head>
      <style>
   .chartWithMarkerOverlay {
       position: relative;
       width: 700px;
   }
   .overlay-marker {
       width: 5px;
       height: 20px;
       position: absolute;
       top: 53px;   /* chartArea top */
       left: 528px; /* chartArea left */
   }
  </style>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);
      var ji= {{ ip|safe }} ;
      console.log(ji);
      function drawChart() {
      if(ji.gender == 0){
        var data = google.visualization.arrayToDataTable([
          ['Age', 'Red Zone', 'Yellow Zone', 'Light Green Zone', 'Dark Green Zone'],
          [0,	2.8,	0.1,	0.3,	11.8],
          [1,	2.9,	0.1,	0.3,	11.7],
          [2,	3.1,	0.1,	0.4,	11.4],
          [3,	3.3,	0.2,	0.3,	11.2],
          [4,	3.5,	0.2,	0.4,	10.9],
          [5,	3.8,	0.2,	0.3,	10.7],
          [6,	4.0,	0.2,	0.4,	10.4],
          [7,	4.2,	0.2,	0.4,	10.2],
          [8,	4.4,	0.2,	0.4,	10.0],
          [9,	4.5,	0.2,	0.5,	9.8],
          [10,	4.7,	0.2,	0.5,	9.6],
          [11,	4.8,	0.3,	0.4,	9.5],
          [12,	5.1,	0.3,	0.4,	9.2],
          [13,	5.1,	0.3,	0.4,	9.2],
          [14,	5.1,	0.3,	0.4,	9.2],
          [15,	5.1,	0.3,	0.4,	9.2],
          [16,	5.6,	0.3,	0.5,	8.6],
          [17,	5.6,	0.3,	0.5,	8.6],
          [18,	5.6,	0.3,	0.5,	8.6],
          [19,	5.6,	0.3,	0.5,	8.6],
          [20,	6.1,	0.3,	0.5,	8.1],
          [21,	6.1,	0.3,	0.5,	8.1],
          [22,	6.1,	0.3,	0.5,	8.1],
          [23,	6.1,	0.3,	0.5,	8.1],
          [24,	6.4,	0.3,	0.6,	7.7],
          [25,	6.4,	0.3,	0.6,	7.7],
          [26,	6.4,	0.3,	0.6,	7.7],
          [27,	6.4,	0.3,	0.6,	7.7],
          [28,	6.7,	0.3,	0.6,	7.4],
          [29,	6.7,	0.3,	0.6,	7.4],
          [30,	6.7,	0.3,	0.6,	7.4],
          [31,	6.7,	0.3,	0.6,	7.4],
          [32,	7.0,	0.3,	0.6,	7.1],
          [33,	7.0,	0.3,	0.6,	7.1],
          [34,	7.0,	0.3,	0.6,	7.1],
          [35,	7.0,	0.3,	0.6,	7.1],
          [36,	7.3,	0.3,	0.6,	6.8],
          [37,	7.3,	0.3,	0.6,	6.8],
          [38,	7.3,	0.3,	0.6,	6.8],
          [39,	7.3,	0.3,	0.6,	6.8],
          [40,	7.5,	0.3,	0.7,	6.5],
          [41,	7.5,	0.3,	0.7,	6.5],
          [42,	7.5,	0.3,	0.7,	6.5],
          [43,	7.5,	0.3,	0.7,	6.5],
          [44,	7.7,	0.3,	0.7,	6.3],
          [45,	7.7,	0.3,	0.7,	6.3],
          [46,	7.7,	0.3,	0.7,	6.3],
          [47,	7.7,	0.3,	0.7,	6.3],
          [48,	7.9,	0.3,	0.7,	6.1],
          [49,	7.9,	0.3,	0.7,	6.1],
          [50,	7.9,	0.3,	0.7,	6.1],
          [51,	7.9,	0.3,	0.7,	6.1],
          [52,	8.1,	0.3,	0.8,	5.8],
          [53,	8.1,	0.3,	0.8,	5.8],
          [54,	8.1,	0.3,	0.8,	5.8],
          [55,	8.1,	0.3,	0.8,	5.8],
          [56,	8.3,	0.3,	0.8,	5.6],
          [57,	8.3,	0.3,	0.8,	5.6],
          [58,	8.3,	0.3,	0.8,	5.6],
          [59,	8.3,	0.3,	0.8,	5.6],
          [60,	8.5,	0.3,	0.8,	5.4],
          [61,	8.5,	0.3,	0.8,	5.4],
          [62,	8.5,	0.3,	0.8,	5.4],
          [63,	8.5,	0.3,	0.8,	5.4],
          [64,	8.7,	0.3,	0.8,	5.2],
          [65,	8.7,	0.3,	0.8,	5.2],
          [66,	8.7,	0.3,	0.8,	5.2],
          [67,	8.7,	0.3,	0.8,	5.2],
          [68,	8.8,	0.4,	0.8,	5.0],
          [69,	8.8,	0.4,	0.8,	5.0],
          [70,	8.8,	0.4,	0.8,	5.0],
          [71,	8.8,	0.4,	0.8,	5.0],
          [72,	9.0,	0.4,	0.8,	4.8],
          [73,	9.0,	0.4,	0.8,	4.8],
          [74,	9.0,	0.4,	0.8,	4.8],
          [75,	9.0,	0.4,	0.8,	4.8],
          [76,	9.2,	0.4,	0.8,	4.6],
          [77,	9.2,	0.4,	0.8,	4.6],
          [78,	9.2,	0.4,	0.8,	4.6],
          [79,	9.2,	0.4,	0.8,	4.6],
          [80,	9.4,	0.4,	0.8,	4.4],
          [81,	9.4,	0.4,	0.8,	4.4],
          [82,	9.4,	0.4,	0.8,	4.4],
          [83,	9.4,	0.4,	0.8,	4.4],
          [84,	9.6,	0.4,	0.9,	4.1],
          [85,	9.6,	0.4,	0.9,	4.1],
          [86,	9.6,	0.4,	0.9,	4.1],
          [87,	9.6,	0.4,	0.9,	4.1],
          [88,	9.8,	0.4,	0.9,	3.9],
          [89,	9.8,	0.4,	0.9,	3.9],
          [90,	9.8,	0.4,	0.9,	3.9],
          [91,	9.8,	0.4,	0.9,	3.9],
          [92,	9.9,	0.5,	0.9,	3.7],
          [93,	9.9,	0.5,	0.9,	3.7],
          [94,	9.9,	0.5,	0.9,	3.7],
          [95,	9.9,	0.5,	0.9,	3.7],
          [96,	10.1,	0.5,	0.9,	3.5],


        ]);

         var options = {
          title: 'GIRL CHILD GROWTH ZONE CHART',
          isStacked: 'true',
          hAxis: {title: 'Age in Weeks',  titleTextStyle: {color: '#333'}},
          vAxis: {title: 'Weight in kg', minValue: 0},
          colors: ['red','orange', 'lightgreen', 'darkgreen']


        };
       }
       else{
        var data = google.visualization.arrayToDataTable([
          ['Age', 'Red Zone', 'Yellow Zone', 'Light Green Zone', 'Dark Green Zone'],
          [0,	2.9,	0.1,	0.3,	11.7],
          [1,	3,	0.2,	0.3,	11.5],
          [2,	3.2,	0.2,	0.4,	11.2],
          [3,	3.5,	0.2,	0.4,	10.9],
          [4,	3.8,	0.2,	0.4,	10.6],
          [5,	4.1,	0.2,	0.4,	10.3],
          [6,	4.3,	0.2,	0.4,	10.1],
          [7,	4.5,	0.3,	0.4,	9.8],
          [8,	4.7,	0.3,	0.4,	9.6],
          [9,	4.9,	0.3,	0.4,	9.4],
          [10,	5.1,	0.3,	0.4,	9.2],
          [11,	5.3,	0.3,	0.4,	9],
          [12,	5.6,	0.3,	0.5,	8.6],
          [13,	5.6,	0.3,	0.5,	8.6],
          [14,	5.6,	0.3,	0.5,	8.6],
          [15,	5.6,	0.3,	0.5,	8.6],
          [16,	6.2,	0.3,	0.5,	8],
          [17,	6.2,	0.3,	0.5,	8],
          [18,	6.2,	0.3,	0.5,	8],
          [19,	6.2,	0.3,	0.5,	8],
          [20,	6.7,	0.3,	0.5,	7.5],
          [21,	6.7,	0.3,	0.5,	7.5],
          [22,	6.7,	0.3,	0.5,	7.5],
          [23,	6.7,	0.3,	0.5,	7.5],
          [24,	7.1,	0.3,	0.5,	7.1],
          [25,	7.1,	0.3,	0.5,	7.1],
          [26,	7.1,	0.3,	0.5,	7.1],
          [27,	7.1,	0.3,	0.5,	7.1],
          [28,	7.4,	0.3,	0.6,	6.7],
          [29,	7.4,	0.3,	0.6,	6.7],
          [30,	7.4,	0.3,	0.6,	6.7],
          [31,	7.4,	0.3,	0.6,	6.7],
          [32,	7.7,	0.3,	0.6,	6.4],
          [33,	7.7,	0.3,	0.6,	6.4],
          [34,	7.7,	0.3,	0.6,	6.4],
          [35,	7.7,	0.3,	0.6,	6.4],
          [36,	7.9,	0.4,	0.6,	6.1],
          [37,	7.9,	0.4,	0.6,	6.1],
          [38,	7.9,	0.4,	0.6,	6.1],
          [39,	7.9,	0.4,	0.6,	6.1],
          [40,	8.2,	0.3,	0.7,	5.8],
          [41,	8.2,	0.3,	0.7,	5.8],
          [42,	8.2,	0.3,	0.7,	5.8],
          [43,	8.2,	0.3,	0.7,	5.8],
          [44,	8.4,	0.3,	0.7,	5.6],
          [45,	8.4,	0.3,	0.7,	5.6],
          [46,	8.4,	0.3,	0.7,	5.6],
          [47,	8.4,	0.3,	0.7,	5.6],
          [48,	8.6,	0.4,	0.6,	5.4],
          [49,	8.6,	0.4,	0.6,	5.4],
          [50,	8.6,	0.4,	0.6,	5.4],
          [51,	8.6,	0.4,	0.6,	5.4],
          [52,	8.8,	0.4,	0.7,	5.1],
          [53,	8.8,	0.4,	0.7,	5.1],
          [54,	8.8,	0.4,	0.7,	5.1],
          [55,	8.8,	0.4,	0.7,	5.1],
          [56,	9.0,	0.4,	0.7,	4.9],
          [57,	9.0,	0.4,	0.7,	4.9],
          [58,	9.0,	0.4,	0.7,	4.9],
          [59,	9.0,	0.4,	0.7,	4.9],
          [60,	9.2,	0.4,	0.7,	4.7],
          [61,	9.2,	0.4,	0.7,	4.7],
          [62,	9.2,	0.4,	0.7,	4.7],
          [63,	9.2,	0.4,	0.7,	4.7],
          [64,	9.4,	0.4,	0.7,	4.5],
          [65,	9.4,	0.4,	0.7,	4.5],
          [66,	9.4,	0.4,	0.7,	4.5],
          [67,	9.4,	0.4,	0.7,	4.5],
          [68,	9.6,	0.4,	0.7,	4.3],
          [69,	9.6,	0.4,	0.7,	4.3],
          [70,	9.6,	0.4,	0.7,	4.3],
          [71,	9.6,	0.4,	0.7,	4.3],
          [72,	9.7,	0.4,	0.8,	4.1],
          [73,	9.7,	0.4,	0.8,	4.1],
          [74,	9.7,	0.4,	0.8,	4.1],
          [75,	9.7,	0.4,	0.8,	4.1],
          [76,	9.9,	0.4,	0.8,	3.9],
          [77,	9.9,	0.4,	0.8,	3.9],
          [78,	9.9,	0.4,	0.8,	3.9],
          [79,	9.9,	0.4,	0.8,	3.9],
          [80,	10.1,	0.4,	0.8,	3.7],
          [81,	10.1,	0.4,	0.8,	3.7],
          [82,	10.1,	0.4,	0.8,	3.7],
          [83,	10.1,	0.4,	0.8,	3.7],
          [84,	10.3,	0.5,	0.7,	3.5],
          [85,	10.3,	0.5,	0.7,	3.5],
          [86,	10.3,	0.5,	0.7,	3.5],
          [87,	10.3,	0.5,	0.7,	3.5],
          [88,	10.5,	0.4,	0.9,	3.2],
          [89,	10.5,	0.4,	0.9,	3.2],
          [90,	10.5,	0.4,	0.9,	3.2],
          [91,	10.5,	0.4,	0.9,	3.2],
          [92,	10.6,	0.5,	0.9,	3],
          [93,	10.6,	0.5,	0.9,	3],
          [94,	10.6,	0.5,	0.9,	3],
          [95,	10.6,	0.5,	0.9,	3],
          [96,	10.8,	0.5,	0.9,	2.8],

      ]);

         var options = {
          title: 'BOY CHILD GROWTH ZONE CHART',
          isStacked: 'true',
          hAxis: {title: 'Age in Weeks',  titleTextStyle: {color: '#333'}},
          vAxis: {title: 'Weight in kg', minValue: 0},
          colors: ['red','orange', 'lightgreen', 'darkgreen']


        };
      }

      function placeMarker(dataTable) {
        var cli = this.getChartLayoutInterface();
        var chartArea = cli.getChartAreaBoundingBox();
        // We enter age and weight of child
        document.querySelector('.overlay-marker').style.top = Math.floor(cli.getYLocation(ji.weight)) - 14 + "px";
        document.querySelector('.overlay-marker').style.left = Math.floor(cli.getXLocation(ji.age+1)) - 22 + "px";
      };

        var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
        google.visualization.events.addListener(chart, 'ready',
        placeMarker.bind(chart, data));
        chart.draw(data, options);
      }
    </script>
  </head>
  <body>
  <center><h1> Growth Zone </h1></center>
  <div class="chartWithMarkerOverlay" >
      <center>
      <div id="chart_div" style="width: 1300px; height: 700px;"></div>
      <div class="overlay-marker">
      <img src="https://png.pngtree.com/png-clipart/20201113/ourmid/pngtree-hand-drawn-baby-clipart-png-image_2423963.jpg"  height="20">
      </div>
    </center>
  </div>

    <center> <h3>CHILD DATA</h3>
    {{ op|safe }} </center>
<!--    <span id="dq"></span>-->
    <br><br><br>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<!--  <button type="submit" class="btn btn-success" onclick="child_list"> Growth Checker </button>>-->
<!--  <button type="submit" class="btn btn-success" onclick=""> Growth Velocity </button>-->
  </body>
  {% endblock content %}
</html>